language: node_js

node_js:
  - "0.10"

before_script:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - ./lein
  - export PATH=$PWD:$PATH
  - lein --version

script: "npm test"
