language: node_js
sudo: false

node_js:
  - "0.10"
  - "4.2"

before_script:
  - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod a+x lein
  - ./lein
  - export PATH=$PWD:$PATH
  - lein --version

script: "npm test"
